NPM: Fix update checker for deprecated deps
When getting possible versions from npm registry we filter out
deprecated versions which meant that packages where all versions where
deprecated returned a nil latest resolvable version which got converted
into a empty version string in the updater checker causing the
exception: "blank strings must not be provided as versions"